AllCops:
  Exclude:
    - '*.gemspec'
    - 'gemfiles/*.gemfile'

Style/MultilineBlockChain:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']