AllCops:
  Exclude:
    - '*.gemspec'

Style/StringLiterals:
  Exclude:
    -'*.gemfile'

Style/MultilineBlockChain:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']